image: Visual Studio 2015
platform:
  - x64
version: 1.0.{build}

build:
  verbosity: normal

install:
- cmd: cinst wget
- cmd: mkdir C:\projects\extension\bin
- cmd: wget https://getcomposer.org/composer.phar -O C:\projects\extension\bin\composer.phar
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64

    wget http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip

    7z x -y php-sdk-binary-tools-20110915.zip -oC:\projects\php-sdk

    C:\projects\php-sdk\bin\phpsdk_setvars.bat

    git clone -q --branch=PHP-7.0.7 https://github.com/php/php-src C:\projects\php-src

    mkdir C:\projects\php-src\ext\amqp
    
    mkdir C:\projects\php-src\ext\phpredis

    git clone https://github.com/pdezwart/php-amqp.git C:\projects\php-src\ext\amqp
    
    cd C:\projects\php-src\ext\amqp
    
    git checkout tags/v1.7.0 C:\projects\php-src\ext\amqp
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    git clone -q --branch=php7 https://github.com/phpredis/phpredis.git C:\projects\php-src\ext\phpredis

    wget http://windows.php.net/downloads/php-sdk/deps-7.0-vc14-x64.7z

    7z x -y deps-7.0-vc14-x64.7z -oC:\projects\php-src
    
    dir C:\projects\php-src

    copy %APPVEYOR_BUILD_FOLDER%\include\*.h C:\projects\php-src\deps\include\
    
    copy %APPVEYOR_BUILD_FOLDER%\lib\*.lib C:\projects\php-src\deps\lib\

    cd C:\projects\php-src

    buildconf.bat

    configure.bat --disable-all --enable-phar --enable-json --enable-hash --enable-ctype --enable-filter --enable-tokenizer --enable-zip --with-iconv --with-openssl --with-dom --with-libxml --enable-cli --enable-amqp=shared --enable-redis=shared --with-config-file-scan-dir=C:\projects\extension\bin\modules.d --with-prefix=C:\projects\extension\bin --with-php-build=deps

    nmake

    nmake install

    copy php.ini-development C:\projects\extension\bin\php.ini
    
artifacts:
  - path: bin
    name: master
    type: zip
