image: Visual Studio 2015
platform:
  - x64
version: 1.0.{build}

build:
  verbosity: normal

install:
- cmd: cinst wget
- cmd: mkdir C:\projects\php-win\build

build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64

    wget http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip

    7z x -y php-sdk-binary-tools-20110915.zip -oC:\projects\php-sdk

    C:\projects\php-sdk\bin\phpsdk_setvars.bat

    git clone -q --branch=PHP-7.0.7 https://github.com/php/php-src C:\projects\php-src

    mkdir C:\projects\php-src\ext\amqp
    
    mkdir C:\projects\php-src\ext\phpredis
    
    mkdir C:\projects\php-src\ext\win32service

    git clone https://github.com/pdezwart/php-amqp.git C:\projects\php-src\ext\amqp
    
    cd C:\projects\php-src\ext\amqp
    
    git checkout tags/v1.7.0 C:\projects\php-src\ext\amqp
    
    svn co http://svn.php.net/viewvc/pecl/win32service/tags/win32service-0.1.0/ C:\projects\php-src\ext\win32service
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    git clone -q --branch=php7 https://github.com/phpredis/phpredis.git C:\projects\php-src\ext\phpredis

    wget http://windows.php.net/downloads/php-sdk/deps-7.0-vc14-x64.7z

    7z x -y deps-7.0-vc14-x64.7z -oC:\projects\php-src
    
    dir C:\projects\php-src

    copy %APPVEYOR_BUILD_FOLDER%\include\*.h C:\projects\php-src\deps\include\
    
    copy %APPVEYOR_BUILD_FOLDER%\lib\*.lib C:\projects\php-src\deps\lib\

    cd C:\projects\php-src

    buildconf.bat

    configure.bat --help | findstr amqp

    configure.bat --help | findstr redis

    configure.bat --help | findstr win32service

    configure.bat --disable-all --disable-zts  --with-openssl --enable-cli --with-amqp=shared --enable-redis=shared --with-config-file-scan-dir=C:\projects\php-win\build\modules.d --with-prefix=C:\projects\php-win\build --with-php-build=deps

    nmake

    nmake install

    copy php.ini-development C:\projects\php-win\build\php.ini

artifacts:
  - path: 'build/ext/php_amqp.dll'
  - path: 'build/ext/php_redis.dll'
